// DB configuration
const dbHost = "localhost";
const dbPort = "3306";
const dbUser = "root";
const dbPass = "@12qwwq21";
// Use the 'desktop' database for IoT desktop storage
const dbName = "desktop";

//Server General Configuration
const serverPort = 3000 

const contextURL = '/iot'; //Project context
const api = '/api'; // API context

//Sensor endpoints
const getLightSensor = '/getLightLevels'
const postLightSensor = '/data'; // Endpoint URL for light level

// LIGHT SENSOR QUERIES
const selectLight = 'SELECT * FROM light';
const selectLightByDate = 'SELECT * FROM light WHERE date between ? and ?';
// Insert light level: client provides the numeric value (stored in column 'value'), date generated by DB/server
const insertLight = 'INSERT INTO light (value, date) values (?, NOW())';


module.exports= {
   dbHost,dbPort,dbUser,dbPass,dbName,serverPort, contextURL,api,
   getLightSensor, postLightSensor,
   selectLight, selectLightByDate, insertLight
}