//File that receives sensor data and processes requests
// (currently only light sensor is implemented)

const mysql = require("../database/MySQLMngr");
const constants = require("../constants")

// counter of post requests
let postCount = 0;

async function insertNewLightLevel(req,res){
    try{
        let query = constants.insertLight;
        var nivel = req.body.nivel;
        // date is generated by the DB using NOW() 
        let params = [nivel];
        // Increment counter and get client info
        postCount += 1;
        const serverTime = new Date().toISOString();
        const clientIp = req.headers['x-forwarded-for'] || req.socket.remoteAddress || req.ip;

        // Log full body and summary so you can see everything the Arduino sends
        console.log(`Received insertLightLevel POST #${postCount} from ${clientIp} at ${serverTime}`);
        console.log(' req.body =', req.body);
        console.log(` summary -> nivel: ${nivel}`);

        // Persist to DB
        console.log('Inserting Data');
        const qResult = await mysql.insertData(query, [nivel]);

        // Log result (gen id / status)
        try {
            const genId = (typeof qResult.getGenId === 'function') ? qResult.getGenId() : qResult.gen_id;
            console.log(`Insert result: status=${qResult.getStatus ? qResult.getStatus() : qResult.status}, gen_id=${genId}`);
        } catch(e){
            console.log('Could not read insert result methods, raw:', qResult);
        }

        res.status(200).json(qResult);
    }catch(error){
        let jsonError = {"status":"error","message": error.message};
        console.log(error);
        res.status(500).send(jsonError);
    }
    }


module.exports = {insertNewLightLevel};
